const fs = require('fs');
const path = require('path');

const distPath = path.join(__dirname, '..', 'dist');
const baseUrl = '/DrawFromMemory/';

console.log('🔧 Starting post-build processing for expo-router + GitHub Pages...');

// Get all HTML files generated by expo-router static rendering
const htmlFiles = fs.readdirSync(distPath)
  .filter(file => file.endsWith('.html'))
  .map(file => path.join(distPath, file));

console.log(`📄 Found ${htmlFiles.length} HTML files to process`);

htmlFiles.forEach(filePath => {
  const fileName = path.basename(filePath);
  let html = fs.readFileSync(filePath, 'utf8');

  // Add <base> tag to set the base URL for all relative paths
  // This works with React hydration and doesn't modify the HTML structure
  if (!html.includes('<base')) {
    html = html.replace(
      '<head>',
      `<head><base href="${baseUrl}">`
    );
  }

  // Fix title if empty (expo-router sometimes generates empty titles)
  if (html.includes('<title data-rh="true"></title>')) {
    html = html.replace(
      '<title data-rh="true"></title>',
      '<title>Merke und Male - Gedächtnistraining</title>'
    );
  }

  fs.writeFileSync(filePath, html);
  console.log(`  ✓ Processed ${fileName}`);
});

console.log('✅ Post-build processing complete!');
console.log(`   Added <base href="${baseUrl}"> to all HTML files`);
