const fs = require('fs');
const path = require('path');

const distPath = path.join(__dirname, '..', 'dist');
const baseUrl = '/DrawFromMemory';
const siteUrl = 'https://s540d.github.io/DrawFromMemory/';
const appTitle = 'Merke und Male - Gedächtnistraining für Kinder';
const appDescription =
  'Merke und Male: Gedächtnistraining für Kinder. Bild kurz ansehen, aus dem Gedächtnis nachzeichnen und vergleichen — spielerisch lernen, kostenlos und werbefrei.';

console.log('🔧 Starting post-build processing for expo-router + GitHub Pages...');

// Get all HTML files generated by expo-router static rendering
const htmlFiles = fs
  .readdirSync(distPath)
  .filter(file => file.endsWith('.html'))
  .map(file => path.join(distPath, file));

console.log(`📄 Found ${htmlFiles.length} HTML files to process`);

// Also need to update the JavaScript bundle to use correct base path
const jsFiles = fs
  .readdirSync(path.join(distPath, '_expo/static/js/web'))
  .filter(file => file.startsWith('entry-') && file.endsWith('.js'))
  .map(file => path.join(distPath, '_expo/static/js/web', file));

htmlFiles.forEach(filePath => {
  const fileName = path.basename(filePath);
  let html = fs.readFileSync(filePath, 'utf8');

  // Rewrite paths for GitHub Pages subpath
  // Match href="/..." but not href="//" (protocol-relative URLs)
  html = html.replace(/href="\/(?!\/)/g, `href="${baseUrl}/`);
  html = html.replace(/src="\/(?!\/)/g, `src="${baseUrl}/`);

  // Fix title if empty (expo-router sometimes generates empty titles)
  if (html.includes('<title data-rh="true"></title>') || html.includes('<title></title>')) {
    html = html.replace(/<title[^>]*><\/title>/, `<title>${appTitle}</title>`);
  } else {
    // Ensure a descriptive, SEO-friendly title even when expo-router already set one
    html = html.replace(/<title>[^<]*<\/title>/, `<title>${appTitle}</title>`);
  }

  // SEO tags: only for index.html (the actual public landing page) —
  // avoids duplicate-content signals across expo-router's other generated pages.
  if (fileName === 'index.html') {
    const seoTags = [
      `<meta name="robots" content="index, follow">`,
      `<meta property="og:title" content="${appTitle}">`,
      `<meta property="og:description" content="${appDescription}">`,
      `<meta property="og:type" content="website">`,
      `<meta property="og:url" content="${siteUrl}">`,
      `<meta property="og:image" content="${siteUrl}feature-graphic.png">`,
      `<meta name="twitter:card" content="summary_large_image">`,
      `<meta name="twitter:title" content="${appTitle}">`,
      `<meta name="twitter:description" content="${appDescription}">`,
      `<meta name="twitter:image" content="${siteUrl}feature-graphic.png">`,
      `<link rel="canonical" href="${siteUrl}">`,
    ].join('\n');

    if (html.includes('<meta name="description"')) {
      // Overwrite the description injected from app.json's web.description with the
      // more detailed SEO copy, and insert the rest of the SEO tags right after it.
      html = html.replace(
        /<meta name="description"[^>]*>/,
        `<meta name="description" content="${appDescription}">\n${seoTags}`,
      );
    } else {
      html = html.replace('</head>', `<meta name="description" content="${appDescription}">\n${seoTags}\n</head>`);
    }
  }

  fs.writeFileSync(filePath, html);
  console.log(`  ✓ Processed ${fileName}`);
});

// Update JavaScript bundle to handle basePath in router
jsFiles.forEach(filePath => {
  const fileName = path.basename(filePath);
  let js = fs.readFileSync(filePath, 'utf8');

  // Replace router base path configuration
  // This ensures client-side navigation works with the subpath
  js = js.replace(/location\.pathname/g, `location.pathname.replace('${baseUrl}', '')`);

  fs.writeFileSync(filePath, js);
  console.log(`  ✓ Updated ${fileName} for subpath routing`);
});

// For SPA mode: Create 404.html that mirrors index.html for GitHub Pages routing
const indexPath = path.join(distPath, 'index.html');
const notFoundPath = path.join(distPath, '404.html');
if (fs.existsSync(indexPath) && !fs.existsSync(notFoundPath)) {
  fs.copyFileSync(indexPath, notFoundPath);
  console.log('  ✓ Created 404.html for SPA routing');
}

console.log('✅ Post-build processing complete!');
console.log(`   Updated all paths with baseUrl: ${baseUrl}`);
