const fs = require('fs');
const path = require('path');

const distPath = path.join(__dirname, '..', 'dist');
const baseUrl = '/DrawFromMemory';

console.log('🔧 Starting post-build processing for expo-router + GitHub Pages...');

// Get all HTML files generated by expo-router static rendering
const htmlFiles = fs.readdirSync(distPath)
  .filter(file => file.endsWith('.html'))
  .map(file => path.join(distPath, file));

console.log(`📄 Found ${htmlFiles.length} HTML files to process`);

htmlFiles.forEach(filePath => {
  const fileName = path.basename(filePath);
  let html = fs.readFileSync(filePath, 'utf8');

  // Add baseUrl prefix to all absolute paths for GitHub Pages subpath
  // This fixes expo-router links to work on GitHub Pages
  html = html.replace(/href="\/(?!\/)/g, `href="${baseUrl}/`);
  html = html.replace(/src="\/(?!\/)/g, `src="${baseUrl}/`);

  // Fix title if empty (expo-router sometimes generates empty titles)
  if (html.includes('<title data-rh="true"></title>')) {
    html = html.replace(
      '<title data-rh="true"></title>',
      '<title>Merke und Male - Gedächtnistraining</title>'
    );
  }

  fs.writeFileSync(filePath, html);
  console.log(`  ✓ Processed ${fileName}`);
});

console.log('✅ Post-build processing complete!');
console.log(`   All links updated with baseUrl: ${baseUrl}`);
